---
- name: Configure Prefix List
  hosts: arista
  gather_facts: false

  tasks:
    - name: Configure Prefix List
      arista.eos.eos_config:
        lines:
          - seq 10 permit 11.11.1.0/24 
          - seq 20 permit 22.22.2.0/24
          - seq 30 permit 33.33.3.0/24
          - seq 90 deny 10.0.0.0/8
        parents: ip prefix-list prefixdemo1
        before: no ip prefix-list prefixdemo1 
 
    - name: show prefix List check if seq 20 exist
      arista.eos.eos_command:
        commands: show ip prefix-list prefixdemo1
        wait_for:
          - result[0] contains "seq 20"

    - name: remove prefix list 20 on prefixdemo1
      arista.eos.eos_config:
        lines:
          - no seq 20 
        parents: ip prefix-list prefixdemo1


    - name: show prefix List check if seq 20 is not exist
      arista.eos.eos_command:
        commands: show ip prefix-list prefixdemo1
        wait_for:
          - result[0] not contains "seq 20"
