---
- name: Cli command playbook
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: network_cli

  tasks:
    - name: Show command
      ansible.netcommon.cli_command:
        command: "delete flash:{{ tower_input | default('') }}"
        check_all: true
        prompt:
          - "Delete filename"
          - "Delete bootflash:"
        answer:
          - ''
          - ''
      when: ansible_network_os is defined

      register: output

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ output.stdout_lines }}"
