---
- name: Configure Route Map
  hosts: arista
  gather_facts: false

  tasks:

    - name: Merge provided configuration with device configuration
      arista.eos.eos_route_maps:
        config:
          - route_map: "mapmerge"
            entries:
              - description: "merged_map"
                action: "permit"
                sequence: 10
                match:
                  router_id: 22
              - description: "newmap"
                action: "deny"
                sequence: 25
                continue_sequence: 45
                match:
                  interface: "Ethernet1"
        state: merged

    - name: Use Route map resource module
      arista.eos.eos_route_maps:
        config:
          - route_map: "mapmerge"
        state: gathered
      register: route_map_config

    - name: debug route_map_config
      ansible.builtin.debug:
        msg: "{{ route_map_config.gathered.entries[0] }}"
      register: flat_map



    # - name: Merge provided configuration with device configuration
    #   arista.eos.eos_route_maps:
    #     config:
    #       - route_map: "mapmerge"
    #         entries:
    #           - description: "merged_map_seq20"
    #             action: "permit"
    #             sequence: 20
    #             match:
    #               router_id: 20

 
         
