---
- name: Configure Route Map
  hosts: arista
  gather_facts: false

  tasks:

    - name: Merge provided configuration with device configuration
      arista.eos.eos_route_maps:
        config:
          - route_map: "mapmerge"
            entries:
              - description: "merged_map"
                action: "permit"
                sequence: 10
                match:
                  router_id: 22
              - description: "newmap"
                action: "deny"
                sequence: 25
                continue_sequence: 45
                match:
                  interface: "Ethernet1"
        state: merged

    - name: check for mapmerge permit or deny 20
      arista.eos.eos_command:
        commands: show route-map mapmerge
        wait_for:
          - result[0] not contains "permit 20"
          - result[0] not contains "deny 20"




    # - name: Merge provided configuration with device configuration
    #   arista.eos.eos_route_maps:
    #     config:
    #       - route_map: "mapmerge"
    #         entries:
    #           - description: "merged_map_seq20"
    #             action: "permit"
    #             sequence: 20
    #             match:
    #               router_id: 20

 
         
