---
- name: Configure VLANs
  hosts: arista
  gather_facts: false

  tasks:

    - name: Use vlans resource module
      arista.eos.eos_vlans:
        state: overridden
        config:
          - name: printers
            vlan_id: 40
          - name: DMZ
            vlan_id: 50
          - name: overridden-vlan
            vlan_id: 60

