---
- name: Var Test
  hosts: localhost
  gather_facts: false
  
  vars:
    map_test: |-
      "gathered": [
            {
              "entries": [
                {
                  "action": "permit",
                  "sequence": 20,
                  "description": "merged_map",
                  "match": {
                    "router_id": "22"
                  }
                },
                {
                  "action": "deny",
                  "sequence": 25,
                  "description": "newmap",
                  "continue_sequence": 45,
                  "match": {
                    "interface": "Ethernet1"
                  }
                }
              ],
              "route_map": "mapmerge"
            },
            {
              "entries": [
                {
                  "action": "deny",
                  "sequence": 45,
                  "sub_route_map": {
                    "name": "mapmerge"
                  },
                  "match": {
                    "ipv6": {
                      "resolved_next_hop": "list1"
                    }
                  },
                  "set": {
                    "metric": {
                      "value": "25",
                      "add": "igp-metric"
                    },
                    "as_path": {
                      "prepend": {
                        "last_as": 2
                      }
                    }
                  }
                }
              ],
              "route_map": "mapmerge2"
            }
          ]

  tasks:

    - name: Debug map Test
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ map_test | from_yaml_all | list  }}"
      register: map_flat

    - name: Map map_flat
      ansible.builtin.assert:
        that:
          - """'"sequence": 20' in map_test""

