---
- name: Configure interface network devices
  hosts: rtr1,rtr2
  gather_facts: false
  tasks:
    - name: Configure device with config
      cli_config:
        config: "{{ lookup('template', '{{ ansible_network_os }}_interface.j2') }}"
